### PR TITLE
typo in action name

### PR DESCRIPTION
**Pull request by gmcdonald**
s/praser/parser

### CODE REVIEW

**Review by lemeurherve — CHANGES_REQUESTED** [review]
Thanks, but there is a typo in the action, it has to be with it, as we can see in linked example workflows like https://github.com/stefanbuck/ristorante/blob/main/.github/workflows/order.yml

**Comment by gmcdonald** [comment]
I see, it looks correct here:

https://github.com/stefanbuck/github-issue-parser

and

https://github.com/marketplace/actions/github-issue-parser

**Review by timja — APPROVED** [review]
If you visit https://github.com/stefanbuck/github-issue-praser you'll see it redirects to the new name.

This was a typo that has been fixed, nice catch

**Review by timja — APPROVED** [review]
If you visit https://github.com/stefanbuck/github-issue-praser you'll see it redirects to the new name.

This was a typo that has been fixed, nice catch

**Review by lemeurherve — APPROVED** [review]

**Pull request merged**
